In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("data.csv")

In [4]:
df.head()

S. No.  Age   BodyTemp.  Fatigue  Cough  BodyPain  SoreThroat  \
0       1   94   98.603205        1      0         1           1   
1       2    1  102.519485        0      1         1           0   
2       3   65  101.799096        1      1         1           2   
3       4   28  103.863706        0      1         0           1   
4       5   75  102.155484        1      0         0           0   

   BreathingDifficulty  Infected  
0                    0         1  
1                    2         1  
2                    1         1  
3                    2         0  
4                    0         0

In [5]:
df.tail()

S. No.  Age   BodyTemp.  Fatigue  Cough  BodyPain  SoreThroat  \
3995    3996   16  103.380497        0      1         0           0   
3996    3997   82  103.224004        0      1         1           0   
3997    3998   73  104.103678        0      1         0           0   
3998    3999   27  104.557772        1      0         0           2   
3999    4000   43  100.320435        0      1         1           0   

      BreathingDifficulty  Infected  
3995                    2         1  
3996                    0         1  
3997                    1         0  
3998                    0         1  
3999                    1         1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   S. No.               4000 non-null   int64  
 1   Age                  4000 non-null   int64  
 2   BodyTemp.            4000 non-null   float64
 3   Fatigue              4000 non-null   int64  
 4   Cough                4000 non-null   int64  
 5   BodyPain             4000 non-null   int64  
 6   SoreThroat           4000 non-null   int64  
 7   BreathingDifficulty  4000 non-null   int64  
 8   Infected             4000 non-null   int64  
dtypes: float64(1), int64(8)
memory usage: 281.3 KB


In [7]:
df['BodyPain'].value_counts()

1    2046
0    1954
Name: BodyPain, dtype: int64

In [8]:
df.describe()

S. No.          Age    BodyTemp.      Fatigue        Cough  \
count  4000.000000  4000.000000  4000.000000  4000.000000  4000.000000   
mean   2000.500000    49.888750   101.542417     0.511000     0.507750   
std    1154.844867    29.115937     2.025641     0.499941     0.500002   
min       1.000000     1.000000    98.000139     0.000000     0.000000   
25%    1000.750000    25.000000    99.793418     0.000000     0.000000   
50%    2000.500000    49.000000   101.581286     1.000000     1.000000   
75%    3000.250000    75.000000   103.274928     1.000000     1.000000   
max    4000.000000   100.000000   104.996821     1.000000     1.000000   

         BodyPain   SoreThroat  BreathingDifficulty    Infected  
count  4000.00000  4000.000000          4000.000000  4000.00000  
mean      0.51150     1.013000             1.016250     0.66275  
std       0.49993     0.823104             0.814341     0.47283  
min       0.00000     0.000000             0.000000     0.00000  
25%       0.00000     0.000000             0.000000     0.00000  
50%       1.00000     1.000000             1.000000     1.00000  
75%       1.00000     2.000000             2.000000     1.00000  
max       1.00000     2.000000             2.000000     1.00000

In [9]:
def data_split(data, ratio):
    np.random.seed(100)
    shuffled = np.random.permutation(len(data))
    test_data_size = int(len(data)*ratio)
    test_data_indices = shuffled[: test_data_size]
    train_data_indices = shuffled[test_data_size :]
    return data.iloc[test_data_indices], data.iloc[train_data_indices]

In [10]:
test_data, train_data = data_split(df, 0.15)

In [11]:
test_data

S. No.  Age   BodyTemp.  Fatigue  Cough  BodyPain  SoreThroat  \
3218    3219   41   98.475234        0      1         1           2   
883      884   50  102.084699        0      1         0           0   
367      368    8  102.302576        0      1         0           2   
2226    2227   83  100.949021        0      0         1           2   
2578    2579   28  102.826798        0      0         1           2   
...      ...  ...         ...      ...    ...       ...         ...   
2707    2708   59   98.503170        1      0         1           2   
1047    1048    2  103.488801        1      1         0           1   
1705    1706   75  101.194203        0      0         0           1   
3718    3719   22  104.957589        0      0         0           2   
2906    2907   60   99.386898        0      1         0           0   

      BreathingDifficulty  Infected  
3218                    1         1  
883                     2         0  
367                     0         0  
2226                    2         1  
2578                    0         0  
...                   ...       ...  
2707                    1         1  
1047                    1         0  
1705                    0         0  
3718                    1         0  
2906                    1         0  

[600 rows x 9 columns]

In [12]:
train_data

S. No.  Age   BodyTemp.  Fatigue  Cough  BodyPain  SoreThroat  \
917      918   93  103.981452        0      1         1           0   
631      632   50   98.632571        1      1         0           0   
2147    2148   17  100.238005        0      1         1           1   
1651    1652   37  103.435843        1      1         0           1   
231      232   42  101.133692        1      0         1           1   
...      ...  ...         ...      ...    ...       ...         ...   
3927    3928   97   99.851941        0      0         1           2   
3943    3944   86   99.432508        0      0         0           2   
1859    1860   94  101.475661        1      0         0           0   
2840    2841   63  104.949295        0      0         0           1   
1544    1545    4  101.683296        1      0         0           0   

      BreathingDifficulty  Infected  
917                     1         1  
631                     1         1  
2147                    2         1  
1651                    0         1  
231                     1         1  
...                   ...       ...  
3927                    2         1  
3943                    0         1  
1859                    2         1  
2840                    1         1  
1544                    1         0  

[3400 rows x 9 columns]

In [13]:
x_train = train_data[['Age', 'BodyTemp.', 'Fatigue', 'Cough', 'BodyPain', 'SoreThroat', 'BreathingDifficulty']].to_numpy()

In [14]:
x_train

array([[ 93.       , 103.9814516,   0.       , ...,   1.       ,
          0.       ,   1.       ],
       [ 50.       ,  98.6325715,   1.       , ...,   0.       ,
          0.       ,   1.       ],
       [ 17.       , 100.2380052,   0.       , ...,   1.       ,
          1.       ,   2.       ],
       ...,
       [ 94.       , 101.4756609,   1.       , ...,   0.       ,
          0.       ,   2.       ],
       [ 63.       , 104.9492948,   0.       , ...,   0.       ,
          1.       ,   1.       ],
       [  4.       , 101.6832961,   1.       , ...,   0.       ,
          0.       ,   1.       ]])

In [15]:
x_test = test_data[['Age', 'BodyTemp.', 'Fatigue', 'Cough', 'BodyPain', 'SoreThroat', 'BreathingDifficulty']].to_numpy()

In [16]:
x_test

array([[ 41.        ,  98.47523402,   0.        , ...,   1.        ,
          2.        ,   1.        ],
       [ 50.        , 102.0846987 ,   0.        , ...,   0.        ,
          0.        ,   2.        ],
       [  8.        , 102.3025758 ,   0.        , ...,   0.        ,
          2.        ,   0.        ],
       ...,
       [ 75.        , 101.1942029 ,   0.        , ...,   0.        ,
          1.        ,   0.        ],
       [ 22.        , 104.9575893 ,   0.        , ...,   0.        ,
          2.        ,   1.        ],
       [ 60.        ,  99.38689774,   0.        , ...,   0.        ,
          0.        ,   1.        ]])

In [17]:
y_train = train_data[['Infected']].to_numpy().reshape(3400, )
y_test = test_data[['Infected']].to_numpy().reshape(600, )

In [18]:
y_train

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [19]:
y_test

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
clf = LogisticRegression()

In [22]:
clf.fit(x_train, y_train)

c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
clf.predict_proba([[38, 99.42, 1, 0, 1, 0, 0]])

array([[0.7454487, 0.2545513]])

In [24]:
y_pred = clf.predict_proba(x_test)

In [25]:
y_pred

array([[0.09298944, 0.90701056],
       [0.37250873, 0.62749127],
       [0.67721865, 0.32278135],
       ...,
       [0.62226421, 0.37773579],
       [0.63534498, 0.36465502],
       [0.52052433, 0.47947567]])

In [26]:
from sklearn.metrics import log_loss

In [27]:
log_loss(y_test, y_pred)

0.4338976979661429